# Generated by Django 4.2.7 on 2024-05-16 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('store', '0003_alter_gallery_options_alter_gallery_gid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartOderItem',
            new_name='CartOrderItem',
        ),
    ]
