# Generated by Django 4.2.7 on 2024-05-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_shipping_amountl_cart_shipping_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
