# Generated by Django 4.2.7 on 2024-06-14 02:01

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_tax_options_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitem',
            name='coupon',
            field=models.ManyToManyField(blank=True, to='store.coupon'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='oid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='bcdefghijklmnopqrstuvwxyz', length=10, max_length=12, prefix='KP', unique=True),
        ),
        migrations.AlterField(
            model_name='cartorderitem',
            name='oid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='bcdefghijklmnopqrstuvwxyz', length=10, max_length=12, prefix='KP', unique=True),
        ),
    ]
