# Generated by Django 4.2.7 on 2024-06-22 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('store', '0011_alter_notification_user_alter_notification_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitem',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.vendor'),
        ),
    ]
